### ISSUE TITLE
[REQ] add license file on GH

### ISSUE THREAD

**Issue by MarcoRavich** [rajmic/declipping2020_codes#1]
Hi there, 1st of all thanks for your awesome work !

Since we've "doxed" it in our [HyMPS project](https://github.com/forart/HyMPS#readme) (under the AUDIO \ [Tools page](https://github.com/forart/HyMPS/blob/main/A_Tools.md#--) \ [Declipping subsection](https://github.com/forart/HyMPS/blob/main/A_Tools.md#declipping-)), can you please add a license for it ?

Expliciting the licensing terms is extremely important to let other devs (and not only) better/faster understand how to reuse/adapt/modify your code in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/rajmic/declipping2020_codes/?label=LICENSE)
(generative URL: https://flat.badgen.net/github/license/rajmic/declipping2020_codes/?label=LICENSE)

Anyway you can easily set a standardized one through the GH's license wizard tool.

Last but not least, let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Thanks in advance.

**Comment by zawi01** [comment]
Hello there!
Thank you for including our work in your project and also for pointing out the missing license file. We understand the issues caused by the file omission and added the necessary license file to fix this issue.
Best regards.

**Comment by MarcoRavich** [comment]
Hi there, thanks, it works now (as you can see above too) !

We hope our "resources collection" will encourage developers' collaborations (or at least provide them some inspiration).
